spring:
  datasource:
    url: jdbc:h2:mem:yas
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  jwt:
     access-token-expiration: 3600000
     refresh-token-expiration: 86400000
#logging:
#  level:
#    root: debug