spring:
  datasource:
    url: jdbc:h2:file:./.database/yas
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jwt:
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  file:
    path: ./.logs/
  level:
    root: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE